### ISSUE TITLE
I wanna a new ver

### ISSUE THREAD

**Issue by woshichenghaibo** [lytedev/netlify-ddns#2]
I wanna a ver excluding jq,how?

**Comment by lytedev** [comment]
You're welcome to fork this repo and give it a shot! You will need some way to process the JSON responses from the Netlify API, but this isn't something I'm willing to work on myself. jq is working very well for me.

Good luck and have fun!

**Comment by woshichenghaibo** [comment]
thanks again

Iv read that :https://answers.netlify.com/t/dynamic-ddns-functionality-on-netlify/8373
and other topics and repos.but there is something wrong to go with my code, the creating function works fine but  i can not delete the old one,please help me if possiable:

#!/usr/bin/env bash
DOMAIN="abc.com"
TTL_SECONDS="120"
SUBDOMAIN="def"
# get a token at https://app.netlify.com/user/applications
ACCESS_TOKEN="__REDACTED__" 
# whether or not
DO_IPV6="1"
#apt install curl
# constants
DNS_ZONE="$(echo "$DOMAIN" | tr '.' '_')"
API="https://api.netlify.com/api/v1"
URL="$API/dns_zones/$DNS_ZONE/dns_records?access_token=$ACCESS_TOKEN"
# setup
CURL_FLAGS="-sL"
curl="curl $CURL_FLAGS"
# fetch IP addresses
MY_IPV4="$($curl 4.ipw.cn)" || \
	{ echo "IPv4 Failed"; exit 4; }
if [ "$DO_IPV6" = "1" ]; then
	MY_IPV6="$($curl 6.ipw.cn)" || \
		{ echo "IPv4 Failed from 'ip'"; exit 5; }
	[ -z "$MY_IPV6" ] && {
		export DO_IPV6="0"
		echo "IPv6 Failed again from 'ip'"
		exit 6
	}
fi
echo "$URL"
# fetch current netlify DNS
CURRENT_DNS_REMOTE=$(curl -sL "$URL" | sed -n -r '/"type": "A"/p; /"type": "AAAA"/p')
echo "remote ip is:"
echo "$CURRENT_DNS_REMOTE"


calc() {
    echo "$CURRENT_DNS_ROMOTE" | 
    sed 's/[{}"\\]//g' |    # 
    tr ':' ',' |            # 
    sed -E 's/([^,]+),'"$1"'([^,]*)/\2/p' |  # 
    sed 's/,$//'            # 
}
setup_netlify_dns_record() {
	echo "Setting up $SUBDOMAIN.$DOMAIN"
	delete_netlify_dns_records_by_subdomain_if_exists "$SUBDOMAIN"
	create_netlify_dns_records "$SUBDOMAIN" && echo "Done setting up $SUBDOMAIN.$DOMAIN"
}

delete_netlify_dns_records_by_subdomain_if_exists() {
	if calc -e "map(select(.hostname == \"$SUBDOMAIN.$DOMAIN\" and .type == \"A\"))[0]" > /dev/null; then
		RECORD_ID="$(calc -r "map(select(.hostname == \"$SUBDOMAIN.$DOMAIN\"))[0].id")"
		curl -X DELETE "$API/dns_zones/$DNS_ZONE/dns_records/$RECORD_ID?access_token=$ACCESS_TOKEN" > /dev/null
	fi
	if [ "$DO_IPV6" = "1" ]; then
		if calc -e "map(select(.hostname == \"$SUBDOMAIN.$DOMAIN\" and .type == \"AAAA\"))[0]" > /dev/null; then
			RECORD_ID="$(calc -r "map(select(.hostname == \"$SUBDOMAIN.$DOMAIN\"))[0].id")"
			curl -X DELETE "$API/dns_zones/$DNS_ZONE/dns_records/$RECORD_ID?access_token=$ACCESS_TOKEN" > /dev/null
		fi
	fi
}



create_netlify_dns_records() {

	if [ "$DO_IPV6" = "1" ]; then
		PAYLOAD_IPv6="{\"type\":\"AAAA\",\"hostname\":\"$SUBDOMAIN\",\"value\":\"$MY_IPV6\",\"ttl\":\"$TTL_SECONDS\"}"
		echo "$PAYLOAD_IPv6" | curl -d @- -H 'content-type:application/json' "$API/dns_zones/$DNS_ZONE/dns_records?access_token=$ACCESS_TOKEN" > /dev/null
  else
    PAYLOAD_IPv4="{\"type\":\"A\",\"hostname\":\"$SUBDOMAIN\",\"value\":\"$MY_IPV4\",\"ttl\":\"$TTL_SECONDS\"}"
	  echo "$PAYLOAD_IPv4" | curl -d @- -H 'content-type:application/json' "$API/dns_zones/$DNS_ZONE/dns_records?access_token=$ACCESS_TOKEN" > /dev/null
	fi
}


echo "IPv4 address is: $MY_IPV4"
[ "$DO_IPV6" = "1" ] && echo "IPv6 address is: $MY_IPV6"
	setup_netlify_dns_record "$s" &
 #create_netlify_dns_records
echo "Waiting for jobs to finish..."
wait
# end

**Comment by lytedev** [comment]
Sorry, I'm not going to be able to support a version of this script that does not use `jq`.

**Comment by woshichenghaibo** [comment]
> Sorry, I'm not going to be able to support a version of this script that does not use `jq`.

got that.

and how to use your project please ?edit env file and upload these into /root/ and then ?

sh /root/netlify-ddns.sh ?

**Comment by lytedev** [comment]
The readme describes basic usage of the application. Beyond that, you will want to read and understand the makefile and script and decide how you want to use it.

**Comment by woshichenghaibo** [comment]
> The readme describes basic usage of the application. Beyond that, you will want to read and understand the makefile and script and decide how you want to use it.

how to uninstall the ddns?

I ran make to configure (my first time) and run ,then it went OK but wrong at the 2rd time.

i trans your code to a .sh file and put into /root/, ran bash /root/ddns.sh :

According to ifconfig.io, my IPv4 address is: 117.139.65.146
My IPv6 address is: 2409:8a00:54bb:6b0:3a14:f49:826d:93e7
Setting up pan1.xxx.ru
Waiting for jobs to finish...
Setting up host2.xxx.ru
Setting up host3.xxx.ru
Done setting up host2.xxx.ru
Done setting up pan1.xxx.ru
Done setting up host3.xxx.ru

But nonthing changed on the netlify site....

**Comment by lytedev** [comment]
It sounds like you installed it using a non-standard method, that is, you did not use `make install-user-timer`, so you cannot use `make uninstall-user-timer`. You will have to manually undo whatever it is you did.

If you want to use the script, you will need to follow the readme. I cannot support specific use-cases where users are doing wacky custom setups, sorry!
